# Generated by Django 3.0.7 on 2020-08-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Progress'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name_plural': 'Results'},
        ),
    ]
