# Generated by Django 3.0.7 on 2020-09-11 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0007_auto_20200909_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='correct',
            new_name='is_correct',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='email_confirmed',
            new_name='is_email_confirmed',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='correctness',
            new_name='is_correct',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
