# Generated by Django 3.0.7 on 2020-09-12 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200911_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='category',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='quiz.Category'),
        ),
        migrations.AddField(
            model_name='result',
            name='correct_answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.Answer'),
        ),
        migrations.AddField(
            model_name='result',
            name='selected_answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.Answer'),
        ),
    ]
