# Generated by Django 3.0.7 on 2020-09-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200912_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='result',
            name='selected_answer',
        ),
    ]
