# Generated by Django 3.0.7 on 2020-09-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20200912_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category'),
        ),
    ]
