# Generated by Django 3.0.7 on 2020-09-12 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20200912_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='category',
        ),
        migrations.AddField(
            model_name='result',
            name='correct_answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.Answer'),
        ),
        migrations.AddField(
            model_name='result',
            name='selected_answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.Answer'),
        ),
    ]
