# Generated by Django 3.0.7 on 2020-09-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20200912_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='correct_answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.Answer'),
        ),
        migrations.AddField(
            model_name='result',
            name='selected_answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.Answer'),
        ),
    ]
